version: "3"
services:
  react-app:
    build:
      dockerfile: Dockerfile
      context: ./client
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - autocomplete-app
    depends_on:
        - api-server
  api-server:
    build:
      dockerfile: Dockerfile
      context: ./server
    image: api-server
    ports:
      - "8080:8080"
    networks:
      - autocomplete-app
    depends_on:
      - elasticSearch 
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - autocomplete-app
    ports:
      - 3005:9200
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - autocomplete-app
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  autocomplete-app:
    driver: bridge
